// Package openapi3 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package openapi3

import (
	"time"
)

// Author defines model for Author.
type Author struct {
	Avatar   *string `json:"avatar"`
	Id       *int32  `json:"id,omitempty"`
	Username *string `json:"username,omitempty"`
}

// Comments defines model for Comments.
type Comments []interface{}

// Dates defines model for Dates.
type Dates struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Post defines model for Post.
type Post struct {
	Author   *Author   `json:"author,omitempty"`
	Comments *Comments `json:"comments,omitempty"`
	Dates    *Dates    `json:"dates,omitempty"`
	Id       *int32    `json:"id,omitempty"`
	Text     *string   `json:"text,omitempty"`
}

// CreateUpdatePostResponse defines model for CreateUpdatePostResponse.
type CreateUpdatePostResponse struct {
	Error  *string `json:"error,omitempty"`
	Result *int32  `json:"result,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error  *string `json:"error,omitempty"`
	Result *int32  `json:"result,omitempty"`
}

// SelectAllPostsResponse defines model for SelectAllPostsResponse.
type SelectAllPostsResponse struct {
	Error  *string      `json:"error,omitempty"`
	Result *interface{} `json:"result,omitempty"`
}

// SelectPostByIdResponse defines model for SelectPostByIdResponse.
type SelectPostByIdResponse struct {
	Error  *string `json:"error,omitempty"`
	Result *Post   `json:"result,omitempty"`
}

// CreateUpdatePostRequest defines model for CreateUpdatePostRequest.
type CreateUpdatePostRequest struct {
	AuthorId *int32  `json:"authorId,omitempty"`
	Text     *string `json:"text,omitempty"`
}

// CreatePostJSONRequestBody defines body for CreatePost for application/json ContentType.
type CreatePostJSONRequestBody CreateUpdatePostRequest

// UpdatePostJSONRequestBody defines body for UpdatePost for application/json ContentType.
type UpdatePostJSONRequestBody CreateUpdatePostRequest
