version: "3.9"
services: 
  api: 
    build: 
      context: .
      dockerfile: ./build/rest-server/Dockerfile
    ports: 
      - "8000:8000"
    command: rest-server -env /api/.env.dev
    environment: 
      DATABASE_HOST: postgres
      JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
      VAULT_ADDRESS: "http://vault:8300"
    depends_on: 
      - postgres
      - vault
      - prometheus
      - jaeger
  prometheus: 
    image: prom/prometheus:v2.30.0
    restart: always
    ports: 
      - "9090:9090"
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  jaeger: 
    image: jaegertracing/all-in-one:1.26
    restart: always
    ports: 
      - "16686:16686"
      - "14268:14268"
  postgres: 
    image: postgres:14rc1-alpine3.14
    restart: always
    environment: 
      POSTGRES_USER: ${PGDB_USERNAME}
      POSTGRES_PASSWORD: ${PGDB_PASSWORD}
      POSTGRES_DB: ${PGDB_NAME}
    ports:
      - "5432:5432"
  vault: 
    image: vault:1.8.2
    restart: always
    cap_add: 
      - IPC_LOCK
    environment: 
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8300"
    ports: 
      - "8300:8300"