// Code generated by counterfeiter. DO NOT EDIT.
package envvartesting

import (
	"art_space/internal/envvar"
	"sync"
)

type FakeProvider struct {
	GetStub        func(string) (string, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		arg1 string
	}
	getReturns struct {
		result1 string
		result2 error
	}
	getReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	WriteSecretStub        func(string, map[string]interface{}) error
	writeSecretMutex       sync.RWMutex
	writeSecretArgsForCall []struct {
		arg1 string
		arg2 map[string]interface{}
	}
	writeSecretReturns struct {
		result1 error
	}
	writeSecretReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProvider) Get(arg1 string) (string, error) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetStub
	fakeReturns := fake.getReturns
	fake.recordInvocation("Get", []interface{}{arg1})
	fake.getMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProvider) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeProvider) GetCalls(stub func(string) (string, error)) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *FakeProvider) GetArgsForCall(i int) string {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	argsForCall := fake.getArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeProvider) GetReturns(result1 string, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) GetReturnsOnCall(i int, result1 string, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) WriteSecret(arg1 string, arg2 map[string]interface{}) error {
	fake.writeSecretMutex.Lock()
	ret, specificReturn := fake.writeSecretReturnsOnCall[len(fake.writeSecretArgsForCall)]
	fake.writeSecretArgsForCall = append(fake.writeSecretArgsForCall, struct {
		arg1 string
		arg2 map[string]interface{}
	}{arg1, arg2})
	stub := fake.WriteSecretStub
	fakeReturns := fake.writeSecretReturns
	fake.recordInvocation("WriteSecret", []interface{}{arg1, arg2})
	fake.writeSecretMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProvider) WriteSecretCallCount() int {
	fake.writeSecretMutex.RLock()
	defer fake.writeSecretMutex.RUnlock()
	return len(fake.writeSecretArgsForCall)
}

func (fake *FakeProvider) WriteSecretCalls(stub func(string, map[string]interface{}) error) {
	fake.writeSecretMutex.Lock()
	defer fake.writeSecretMutex.Unlock()
	fake.WriteSecretStub = stub
}

func (fake *FakeProvider) WriteSecretArgsForCall(i int) (string, map[string]interface{}) {
	fake.writeSecretMutex.RLock()
	defer fake.writeSecretMutex.RUnlock()
	argsForCall := fake.writeSecretArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeProvider) WriteSecretReturns(result1 error) {
	fake.writeSecretMutex.Lock()
	defer fake.writeSecretMutex.Unlock()
	fake.WriteSecretStub = nil
	fake.writeSecretReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProvider) WriteSecretReturnsOnCall(i int, result1 error) {
	fake.writeSecretMutex.Lock()
	defer fake.writeSecretMutex.Unlock()
	fake.WriteSecretStub = nil
	if fake.writeSecretReturnsOnCall == nil {
		fake.writeSecretReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeSecretReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	fake.writeSecretMutex.RLock()
	defer fake.writeSecretMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ envvar.Provider = new(FakeProvider)
