# Generated by Django 3.1.6 on 2021-02-11 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('composition', '0003_auto_20210211_0948'),
        ('comments', '0002_auto_20210211_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composition.art')),
                ('comment_author', models.ForeignKey(default='self', on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
            ],
            options={
                'db_table': 'comment_on_art',
            },
        ),
        migrations.CreateModel(
            name='AudioComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composition.audio')),
                ('comment_author', models.ForeignKey(default='self', on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
            ],
            options={
                'db_table': 'comment_on_music',
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
