# Generated by Django 3.1.6 on 2021-02-11 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Music', 'Music'), ('Art', 'Art')], max_length=255)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('picture', models.ImageField(blank=True, upload_to='art/')),
                ('picture_name', models.CharField(default='Unnamed', max_length=255)),
                ('direction', models.CharField(blank=True, max_length=255)),
                ('composition_author', models.ForeignKey(default='self', on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile', verbose_name='Composition author')),
            ],
            options={
                'db_table': 'art',
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Music', 'Music'), ('Art', 'Art')], max_length=255)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('track', models.FileField(blank=True, upload_to='audio/')),
                ('cover', models.ImageField(blank=True, upload_to='cover/')),
                ('track_name', models.CharField(default='Unnamed', max_length=255)),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('producer', models.CharField(blank=True, max_length=255)),
                ('featured', models.CharField(blank=True, max_length=255)),
                ('composition_author', models.ForeignKey(default='self', on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile', verbose_name='Composition author')),
            ],
            options={
                'db_table': 'audio',
            },
        ),
        migrations.CreateModel(
            name='AudioComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composition.audio')),
                ('comment_author', models.ForeignKey(default='self', on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
            ],
            options={
                'db_table': 'comment_on_music',
            },
        ),
        migrations.CreateModel(
            name='ArtComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composition.art')),
                ('comment_author', models.ForeignKey(default='self', on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
            ],
            options={
                'db_table': 'comment_on_art',
            },
        ),
    ]
