# Generated by Django 3.1.6 on 2021-02-11 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('composition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='composition_author',
            field=models.ForeignKey(default='self.__str__()', on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile', verbose_name='Composition author'),
        ),
        migrations.AlterField(
            model_name='artcomment',
            name='comment_author',
            field=models.ForeignKey(default='self.__str__()', on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='composition_author',
            field=models.ForeignKey(default='self.__str__()', on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile', verbose_name='Composition author'),
        ),
        migrations.AlterField(
            model_name='audiocomment',
            name='comment_author',
            field=models.ForeignKey(default='self.__str__()', on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile'),
        ),
    ]
