# Generated by Django 3.1.6 on 2021-02-11 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('composition', '0002_auto_20210211_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiocomment',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='audiocomment',
            name='comment_author',
        ),
        migrations.AlterField(
            model_name='art',
            name='composition_author',
            field=models.ForeignKey(default='self', on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile', verbose_name='Composition author'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='composition_author',
            field=models.ForeignKey(default='self', on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile', verbose_name='Composition author'),
        ),
        migrations.DeleteModel(
            name='ArtComment',
        ),
        migrations.DeleteModel(
            name='AudioComment',
        ),
    ]
